### ISSUE TITLE
iCloud Application Folders Do Not Sync

### ISSUE THREAD

**Issue by RusticPotatoes** [mandarons/icloud-docker#24] opened 2021-08-01 17:10 UTC
**Describe the bug**
Application folders do not sync, root folders are created but no sub folders or files are downloaded. 

**To Reproduce**
1. For instance, a note taking app like Obsidian creates an application folder on iCloud Drive to have all your notes synced across all devices. 
2. In the configuration, comment out any and all include folder or include files so it syncs everything. 
3. Folders get created but there are no contents, empty root folder Obsidian.

**Expected behavior**
Should recursively download and sync all files, including application specific folders.

**Screenshots**
Screenshot of an iCloud Application folder, for example Obsidian:
![2D107BC4-0B74-4056-A022-A8DAE1F7E7F5](https://user-images.githubusercontent.com/3542090/127779543-f04ab9fe-54fe-4304-a41e-88cf22f17f6d.jpeg)
 
Screenshot of Docker iCloud data output folder: 
![4B372B31-350A-4F71-AF00-5010EC921AE6](https://user-images.githubusercontent.com/3542090/127779445-659a3b87-2194-451a-8904-382b7583d86d.jpeg)

**Comment by mandarons** [comment] 2021-08-01 17:50
@RusticPotatoes : Looking into it. Which version are you using? Can you please share your `config.yaml` file? I am not able to reproduce it.

**Comment by RusticPotatoes** [comment] 2021-08-02 12:28
[config.yaml.txt](https://github.com/mandarons/icloud-drive-docker/files/6916820/config.yaml.txt)

**Comment by mandarons** [comment] 2021-08-02 20:37
@RusticPotatoes : Thanks. Looks like you have verbose mode enabled (`verbose: true`) in the config file. Do you see any error message in container logs? If yes, please share.

**Comment by RusticPotatoes** [comment] 2021-08-02 23:10
@mandarons , the logs don't show anything.  Because the folder is created it just skips over it as if it is empty, no logs nothing.  If there wasn't a folder it would log the folder creation, but wont create any sub directories.  

Screenshot below of what I'm talking about from my iPad, from the files app you can see folders with icons on them do not sync any contents. Not sure if it's a permissions issue or maybe a limitation with pyiCloud.  Is there a way to query and see what pyiCloud sees in the folders?

![IMG_7628](https://user-images.githubusercontent.com/3542090/127934243-697cf25b-9ce5-40e9-83aa-2752b3d0de7a.jpeg)

**Comment by mandarons** [comment] 2021-08-03 03:31
@RusticPotatoes that's weird. I see that you don't have file extension filters. So, it should sync all the files. 

Possibilities: 

* There is a known issue in PyiCloud related to some files not syncing (https://github.com/picklepete/pyicloud/pull/316). Not sure if it is related. 
* Permissions issue.

Troubleshoot suggestions:
* I know that `Files` app is very unstable. Do you see these files on `iCloud.com`? 
* `PyiCloud` has some code samples that you can try: [Code Samples](https://github.com/picklepete/pyicloud/blob/master/CODE_SAMPLES.md) See if you can figure out type of files/folders in these Application Folders.
* If everything fails, I can help you troubleshoot in over Discord or something.

**Comment by RusticPotatoes** [comment] 2021-08-03 14:09
@mandarons my responses below,

Possibilities:

- Keyerror data token could be an issue, a few times I've had to re-authenticate
- Not sure how to check if it's a permissions issue

Troubleshooting suggestions:

- Yes I see the files on iCloud.com
- When I get to the last step of the code sample I get a 503 error 
`File Storage
Traceback (most recent call last):
  File "<ipython-input-26-a3164ef543eb>", line 2, in <module>
    print(api.files.dir())
  File "C:\tools\Anaconda3\lib\site-packages\pyicloud\services\ubiquity.py", line 43, in __getattr__
    return getattr(self.root, attr)
  File "C:\tools\Anaconda3\lib\site-packages\pyicloud\services\ubiquity.py", line 20, in root
    self._root = self.get_node(0)
  File "C:\tools\Anaconda3\lib\site-packages\pyicloud\services\ubiquity.py", line 29, in get_node
    request = self.session.get(self.get_node_url(node_id))
  File "C:\tools\Anaconda3\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\pyicloud\base.py", line 130, in request
    self._raise_error(response.status_code, response.reason)
  File "C:\tools\Anaconda3\lib\site-packages\pyicloud\base.py", line 186, in _raise_error
    raise api_error`
- Sure, we can chat on discord let me know the invite link or username.

**Comment by RusticPotatoes** [comment] 2021-08-03 14:16
@mandarons , I wonder if this is my issue https://github.com/picklepete/pyicloud/pull/343

**Comment by mandarons** [comment] 2021-08-03 14:41
@RusticPotatoes: Yes, looks like https://github.com/picklepete/pyicloud/pull/343 is the solution. We will have to wait until it gets merged.

**Comment by simonszu** [comment] 2021-11-22 12:26
It looks like the pyicloud project is dead. There have been no commits since February, and issues are unanswered.

**Comment by mandarons** [comment] 2021-11-22 22:47
> It looks like the pyicloud project is dead. There have been no commits since February, and issues are unanswered.

Yeah, that's sad. I will see if I can fork their repo, pull in some changes and use it instead. I have plan (but not time yet) to build pyicloud-like library for files and photos, to enable two-way sync.

**Closed as completed** 2022-01-23 04:06 UTC
Labels: bug, good first issue, blocked-by-icloudpy
