### ISSUE TITLE
[BUG] Crash with KeyError: 'data_token'

### ISSUE THREAD

**Issue by AlexMikhalev** [mandarons/icloud-docker#11] opened 2021-04-07 19:25 UTC
I tried to use newest version published and successfully authenticated and started downloading all files in Documents folder, then suddenly icloud crashed on sync: 

```
icloud-drive    | No changes detected. Skipping the file /app/drive/Documents/for_blog_post/Figure_1.png
icloud-drive    | No changes detected. Skipping the file /app/drive/Documents/Foundation Ontologies for Distributed Multi-Agent systems/Screenshot 2020-02-11 at 09.55.18.png
icloud-drive    | No changes detected. Skipping the file /app/drive/Documents/Foundation Ontologies for Distributed Multi-Agent systems/Screenshot 2020-02-11 at 10.00.59.png
icloud-drive    | No changes detected. Skipping the file /app/drive/Documents/Foundation Ontologies for Distributed Multi-Agent systems/Screenshot 2020-02-11 at 10.05.13.png
icloud-drive    | No changes detected. Skipping the file /app/drive/Documents/Foundation Ontologies for Distributed Multi-Agent systems/Screenshot 2020-02-11 at 10.10.45.png
icloud-drive    | No changes detected. Skipping the file /app/drive/Documents/Foundation Ontologies for Distributed Multi-Agent systems/Screenshot 2020-02-11 at 10.22.21.png
icloud-drive    | No changes detected. Skipping the file /app/drive/Documents/Foundation Ontologies for Distributed Multi-Agent systems/Screenshot 2020-02-11 at 10.26.28.png
icloud-drive    | No changes detected. Skipping the file /app/drive/Documents/Foundation Ontologies for Distributed Multi-Agent systems/Screenshot 2020-02-11 at 10.34.40.png
icloud-drive    | Downloading /app/drive/Documents/Foundation Ontologies for Distributed Multi-Agent systems.md ...
icloud-drive    | Downloading /app/drive/Documents/Foundation Ontologies for Distributed Multi-Agent systems.textbundle ...
icloud-drive    | Traceback (most recent call last):
icloud-drive    |   File "/app/./src/main.py", line 6, in <module>
icloud-drive    |     sync.sync_drive()
icloud-drive    |   File "/app/src/sync.py", line 159, in sync_drive
icloud-drive    |     sync_directory(drive=api.drive, destination_path=destination_path, root=destination_path,
icloud-drive    |   File "/app/src/sync.py", line 136, in sync_directory
icloud-drive    |     files.update(sync_directory(drive=item, destination_path=new_folder, items=item.dir(), root=root,
icloud-drive    |   File "/app/src/sync.py", line 141, in sync_directory
icloud-drive    |     process_file(item=item, destination_path=destination_path,
icloud-drive    |   File "/app/src/sync.py", line 102, in process_file
icloud-drive    |     download_file(item=item, local_file=local_file, verbose=verbose)
icloud-drive    |   File "/app/src/sync.py", line 82, in download_file
icloud-drive    |     with item.open(stream=True) as response:
icloud-drive    |   File "/usr/local/lib/python3.9/site-packages/pyicloud/services/drive.py", line 270, in open
icloud-drive    |     return self.connection.get_file(self.data["docwsid"], **kwargs)
icloud-drive    |   File "/usr/local/lib/python3.9/site-packages/pyicloud/services/drive.py", line 58, in get_file
icloud-drive    |     url = response.json()["data_token"]["url"]
icloud-drive    | KeyError: 'data_token'
```

**Comment by mandarons** [comment] 2021-04-07 23:43
@AlexMikhalev: Thanks for submitting the issue. 👍 

It looks like the underlying pyiCloud library failed to process iCloud server response. There is an open PR https://github.com/picklepete/pyicloud/pull/316 to fix this. I guess, we will have to wait for the fix to get onto master/main branch of pyicloud library. Also, this seem to be the problem with Keynote files. They don't have data_token but have package_token instead and pyicloud library is failing to process it correctly. 👎 

For now, I can update the code to handle KeyError exception, skip this file and continue the operation without crashing. Would that be okay?

**Comment by mandarons** [comment] 2021-04-09 00:25
Fixed in [Release 1.1.1](https://github.com/mandarons/icloud-drive-docker/releases/tag/v1.1.1)

**Comment by AlexMikhalev** [comment] 2021-04-09 18:25
Hello, @mandarons,
How can I make sure I am running the latest release with docker? Crashed at the same place:

```
Downloading /app/drive/Documents/Foundation Ontologies for Distributed Multi-Agent systems.textbundle ...
Traceback (most recent call last):
  File "/app/./src/main.py", line 6, in <module>
    sync.sync_drive()
  File "/app/src/sync.py", line 159, in sync_drive
    sync_directory(drive=api.drive, destination_path=destination_path, root=destination_path,
  File "/app/src/sync.py", line 136, in sync_directory
    files.update(sync_directory(drive=item, destination_path=new_folder, items=item.dir(), root=root,
  File "/app/src/sync.py", line 141, in sync_directory
    process_file(item=item, destination_path=destination_path,
  File "/app/src/sync.py", line 102, in process_file
    download_file(item=item, local_file=local_file, verbose=verbose)
  File "/app/src/sync.py", line 82, in download_file
    with item.open(stream=True) as response:
  File "/usr/local/lib/python3.9/site-packages/pyicloud/services/drive.py", line 270, in open
    return self.connection.get_file(self.data["docwsid"], **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyicloud/services/drive.py", line 58, in get_file
    url = response.json()["data_token"]["url"]
KeyError: 'data_token'
 ➜  icloud docker pull mandarons/icloud-drive
Using default tag: latest
latest: Pulling from mandarons/icloud-drive
Digest: sha256:1abf9de16972b6ed3410aabb2a631c99b88aa66fbec2c96bb124fc743ccfe9ba
Status: Image is up to date for mandarons/icloud-drive:latest
docker.io/mandarons/icloud-drive:latest

```

**Comment by mandarons** [comment] 2021-04-09 23:14
That's weird. Did you recreate the container after pulling the latest image? If yes, please share output of following command:

`docker exec -it <name_of_the_container> /bin/sh -c "sed -n 87p src/sync.py`

**Comment by AlexMikhalev** [comment] 2021-04-10 20:17
docker exec -it icloud-drive /bin/sh -c "sed -n 87p src/sync.py"
    except (exceptions.PyiCloudAPIResponseException, FileNotFoundError) as e: 

I see - it should have an exception. Let me try to re-create.

**Comment by AlexMikhalev** [comment] 2021-04-11 21:32
works after re-creating - I restarted container after pool and it wasn't enough.

**Comment by robdejonge** [comment] 2022-01-03 04:23
Brought up the container, entered the password, then: 
```
% docker exec -it icloud-drive /bin/sh -c "sed -n 87p src/sync.py"
        os.utime(local_file, (item_modified_time, item_modified_time))

```
I'm still getting the `data_token` errors though. 

Am I doing something wrong?

**Comment by mandarons** [comment] 2022-01-24 14:55
@robdejonge : which version are you using?

**Comment by robdejonge** [comment] 2022-01-25 03:46
@mandarons I don't know how to find the version number, but given I downloaded it more than 10 days and less than 5 months ago, I'm going to venture I'm using version 1.5.0 of the image published on Docker Hub. Which I'm hoping will have had any changes made to the code before April 12th last year.

**Comment by mandarons** [comment] 2022-01-26 01:08
Okay. Please try again with version 1.7.0.

**Comment by robdejonge** [comment] 2022-01-26 04:00
Stopped and removed the container, removed the image, started `docker-compose` so that the latest image would be downloaded. Same result, still full of `data_token` errors. 

My `docker-compose.yaml`: 
```
version: "3.4"
services:
  icloud-drive:
    image: mandarons/icloud-drive
    environment:
      - PUID=1001
      - GUID=1001
    container_name: icloud-drive
    restart: "no"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /host/path/to/config.yaml:/app/config.yaml
      - /host/path/to/drive:/app/drive
```

My `config.yaml`: 
```
app:
  credentials:
    username: xxx
  sync_interval: 300
  root: icloud
  verbose: true
drive:
  destination: drive
  remove_obsolete: true
```

For what it's worth: A total of 49 files out of 965 (5%) yielded this error. I could not discern any common characteristics among those files, in terms of file types or something.

**Comment by mandarons** [comment] 2022-01-26 20:01
Can you paste error details with traceback information?

**Comment by robdejonge** [comment] 2022-01-27 05:22
There is no traceback information. The container log shows 49 instances of 
```
Failed to download /app/icloud/drive/<path>/<to>/<file>: 'data_token'
```
In my case, 38 of them are `.pages` documents, but I also have many such documents that downloaded just fine. 
Several other file types, in all cases also other documents of the same type that downloaded just fine.

**Comment by mandarons** [comment] 2022-01-27 15:58
Previous fix was to skip the erroneous file. Root cause of this issue is now in [icloudpy](https://github.com/mandarons/icloudpy) library, which I should be able to fix now. Reopening this issue ...

**Closed as completed** 2022-01-28 00:38 UTC
Labels: bug

**Comment by mandarons** [comment] 2022-01-28 01:33
@robdejonge : Feel free to try the fix with docker image tag `mandarons/icloud-drive:main` (from `main` branch).

**Comment by robdejonge** [comment] 2022-01-28 04:49
Not only did you fix the issue (all the files previously triggering a `data_token` error no longer do), it seems as if the whole thing executes a lot faster. Thanks very much for the effort to getting this resolved!
